# Root logger option
# Keep default at INFO for lower runtime overhead; enable DEBUG only for short diagnostics.
log4j.rootLogger=INFO, global
 
# RollingFileAppender 
log4j.appender.global=org.apache.log4j.RollingFileAppender 
log4j.appender.global.File=synclite_consolidator.trace 
log4j.appender.global.layout=org.apache.log4j.PatternLayout 
log4j.appender.global.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p [%c{1}] - %m%n